name: blog
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/medz/blog-server-with-dart

environment:
  sdk: ^3.2.3

dependencies:
  orm: 5.2.0
  spry: ^5.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
